version: '3.4'

services:

  nodered:
    image: jamescarl20190101/docker-raspberry-pi-nodered:0.20.5 
#nodered/node-red:1.0.3-10-arm32v7
    hostname: nodered
    ports:
      # NodeRED unencrypted TCP 1880
      - mode: host
        target: 1880
        published: 1880
        protocol: tcp
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
    networks:
      - nodered-net1
    volumes:
      - type: bind
        source: /mnt/nodered
        target: /data/.node-red
    deploy:
      mode: global
      labels:
        local.description: "NodeRED"
      restart_policy:
        condition: on-failure

networks:
  nodered-net1:

